ALTER TABLE users ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT NULL;

ALTER TABLE users ALTER COLUMN updated_at DROP NOT NULL;
ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT NULL;

ALTER TABLE pings ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE pings ALTER COLUMN created_at SET DEFAULT NULL;

ALTER TABLE pings ALTER COLUMN updated_at DROP NOT NULL;
ALTER TABLE pings ALTER COLUMN updated_at SET DEFAULT NULL;
